apiVersion: apps/v1
kind: Deployment
metadata:
  name: apacheweb
  labels:
    app: apacheweb
spec:
  selector:
    matchLabels:
      app: apacheweb
  replicas: 1
  template:
    metadata:
      labels:
        app: apacheweb
    spec:
      containers:
      - name: apacheweb
        image: ubuntu:20.04
        command: ["/bin/sh", "-c", "apt update -y && apt install -y apache2 && apt install -y git && git clone https://github.com/josemasse/english && rm -R /var/www/html/* && cp -R english/* /var/www/html/ &&service apache2 start && tail -f /dev/null"]
        ports:
        - name: http
          containerPort: 80
        env:
        - name: DEBIAN_FRONTEND
          value: noninteractive
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: apacheweb
spec:
  selector:
    app: apacheweb
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apacheweb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apacheweb
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
