apiVersion: apps/v1

kind: Deployment

metadata:

  name: bird

spec:

  replicas: 1

  selector:

    matchLabels:

      app: bird

  template:

    metadata:

      labels:

        app: bird

    spec:

      containers:

        - name: bird

          image: bhargavbunny94/flappybird

          ports:

            - containerPort: 80
          resources:

            limits:

              cpu: "1"

            requests:

              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: bird
spec:
  selector:
    app: bird
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bird
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bird
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5

