apiVersion: apps/v1

kind: Deployment

metadata:

  name: game2048

spec:

  replicas: 1

  selector:

    matchLabels:

      app: game2048

  template:

    metadata:

      labels:

        app: game2048

    spec:

      containers:

        - name: game2048

          image: runseb/2048:latest

          ports:

            - containerPort: 80
          resources:

            limits:

              cpu: "1"

            requests:

              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: game2048
spec:
  selector:
    app: game2048
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: game2048
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: game2048
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5
