apiVersion: apps/v1

kind: Deployment

metadata:

  name: tetris

spec:

  replicas: 1

  selector:

    matchLabels:

      app: tetris

  template:

    metadata:

      labels:

        app: tetris

    spec:

      containers:

        - name: tetris

          image: uzyexe/tetris:latest

          ports:

            - containerPort: 80
          resources:

            limits:

              cpu: "1"

            requests:

              cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: tetris
spec:
  selector:
    app: tetris
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tetris
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tetris
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 5

